# Pensando vendor dependencies manifest
# Please refer docs/vendor.md for more details.

# required lists packages needed by dev tools that aren't improted in the project
# prune will not touch these packages. Please add newer packages to required with caution.
# Maintain required lists in lexicographical order
required = ["github.com/GeertJohan/go.rice",
            "github.com/GeertJohan/go.rice/rice",
            "github.com/GeertJohan/go.rice/embedded",
            "github.com/gogo/protobuf/protoc-gen-gofast",
            "github.com/golang/dep",
            "github.com/golang/dep/cmd/dep",
            "github.com/golang/lint",
            "github.com/golang/lint/golint",
            "github.com/golang/mock/mockgen",
            "github.com/golang/mock/gomock",
            "github.com/golang/protobuf/protoc-gen-go/generator",
            "github.com/golang/protobuf/protoc-gen-go/grpc",
            "github.com/golang/protobuf/ptypes/any",
            "github.com/minio/minio-go",
            "github.com/pensando/grpc-gateway/protoc-gen-grpc-gateway",
            "github.com/pensando/grpc-gateway/protoc-gen-swagger/genswagger",
            "golang.org/x/tools/cmd/goimports",
            "github.com/haya14busa/gopkgs/cmd/gopkgs",
            "github.com/cpuguy83/go-md2man",
            "github.com/russross/blackfriday",
            "layeh.com/radius/cmd/radius-dict-gen",
            "github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc",
            "github.com/cheggaaa/pb",
	    "github.com/mgechev/revive"]

# Hash contents of docker repo is different on CI machines. Since this is used only by some test targets, it is
# safe to add it to noverify list, which will ensure that dep check will not compare vendor tree has for this constraint.
# Make sure we don't add anything else (imported by venice/agent or any production go code) to noverify, unless absolutely needed.
noverify = ["github.com/docker/docker", "github.com/vmware/govmomi"]

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/c9s/goprocinfo"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/hdrhistogram"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "=0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[override]]
   name = "github.com/googleapis/gnostic"
   version = "=v0.2.0"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[override]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  branch = "master"
  name = "github.com/grandcat/zeroconf"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.6"

[[override]]
  name = "github.com/hpcloud/tail"
  revision = "000912af8de2d2b9d184786b4cf4c3542b7884e5"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "=1.0.1"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  branch = "master"

[[constraint]]
  revision = "c851e5e1525d93917e37121f3aa6fcef28bff52f"
  name = "github.com/pensando/grpc-gateway"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netns"

[[constraint]]
  name = "github.com/willf/bitset"
  version = "1.1.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "golang.org/x/net"
  branch = "release-branch.go1.11"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.7.5"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.11"

[[override]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.58"

# Override here is needed as k8s.io/api repo is not standardized yet. ToDo
# Move to a released version when we upgrade all k8s packages

# Needed for cni plugin types compatibility. ToDo Use a released version
[[override]]
  name = "github.com/appc/cni"
  revision = "98ff61aac32dcf2eb3044a0d5e5f1814837b3c75"

# Needed for cni plugin types compatibility. ToDo Move to a released version
[[override]]
  name = "github.com/containernetworking/cni"
  revision = "98ff61aac32dcf2eb3044a0d5e5f1814837b3c75"

[[override]]
  name = "github.com/vmware/govmomi"
  revision = "a9b0a80589c6b412b139f2cec86efff6a40b7ddc"

# Overrride needed for supporting mux.RunOnAddr() call. ToDo Move to gorilla mux
[[override]]
  name = "github.com/go-martini/martini"
  revision = "fe605b5cd210047ae3bb73d2b69a5b912a9b423d"

# Override needed for supporting the correct db.Writes in TestServer. ToDo Use compatible semver
[[override]]
  name = "github.com/influxdata/influxdb"
  revision = "8b18cc445653866f71a59002f2f8524721a5d27e"

[[constraint]]
  name = "github.com/influxdata/influxql"
  branch = "master"
# Override needed for the handling unmarshal errors in Agent REST Server and NMD REST Server. ToDo Use compatible semver
[[override]]
  name = "github.com/coreos/etcd"
  version = "=3.3.13"

# Override needed for compatible keymgr
[[override]]
  revision = "eda1d775a087f2a96fec7c7876ea94dea43e6027"
  name = "github.com/miekg/pkcs11"

[[override]]
  name = "go.uber.org/zap"
  version = "=1.10.0"

[[override]]
  revision = "805b8bc09a50b1f1dc8bc0f8e9fbf32237aa333c"
  name = "github.com/pensando/goexpect"

# Override needed as the master commit needs go 1.12 and org/x/sys needs a upgrade which might affect other things
[[override]]
  revision = "640d790d2bdd9420ffa04d44e5568b80260e28dc"
  name = "github.com/mdlayher/raw"

[[override]]
  revision = "e9c59d9d2f1bf69b3f30f99b7b0ebf75d28c7799"
  name = "github.com/mdlayher/arp"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.0"

[[constraint]]
  name = "github.com/haya14busa/gopkgs"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false
    unused-packages = false
  [[prune.project]]
    name = "github.com/golang/protobuf"
    non-go = false
    unused-packages = false
  [[prune.project]]
    name = "github.com/pensando/grpc-gateway"
    unused-packages = false
    non-go = false
  [[prune.project]]
    name = "github.com/spf13/cobra"
    unused-packages = false


[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/cpuguy83/go-md2man"
  version = "1.0.8"

[[constraint]]
  name = "github.com/pkg/sftp"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "layeh.com/radius"

[[constraint]]
  name = "github.com/minio/minio"
  version = "RELEASE.2018-12-06T01-27-43Z"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.7"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/jeromer/syslogparser"

[[constraint]]
  branch = "master"
  name = "github.com/RackSec/srslog"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.7"

[[constraint]]
  name = "github.com/cayleygraph/cayley"
  revision = "e4023df2f0cecef7aae93ee9c44848fe359e6611"

[[constraint]]
  name = "github.com/sethvargo/go-password"
  version = "0.1.2"

[[constraint]]
  name = "github.com/go-logfmt/logfmt"
  version = "0.3.0"


[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.25"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.3"
