# Pensando vendor dependencies manifest
# Please refer docs/vendor.md for more details.

# required lists packages needed by dev tools that aren't improted in the project
# prune will not touch these packages. Please add newer packages to required with caution.
# Maintain required lists in lexicographical order
required = ["github.com/GeertJohan/go.rice",
            "github.com/GeertJohan/go.rice/rice",
            "github.com/gogo/protobuf/protoc-gen-gofast",
            "github.com/golang/dep",
            "github.com/golang/dep/cmd/dep",
            "github.com/golang/lint",
            "github.com/golang/lint/golint",
            "github.com/golang/mock/mockgen",
            "github.com/golang/protobuf/protoc-gen-go/generator",
            "github.com/golang/protobuf/protoc-gen-go/grpc",
            "github.com/minio/minio-go",
            "github.com/pensando/grpc-gateway/protoc-gen-grpc-gateway",
            "github.com/pensando/grpc-gateway/protoc-gen-swagger/genswagger",
            "golang.org/x/tools/cmd/goimports"]

[[constraint]]
  branch = "master"
  name = "github.com/GeertJohan/go.rice"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/c9s/goprocinfo"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/hdrhistogram"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[override]]
  name = "github.com/gorilla/mux"
  revision = "757bef944d0f21880861c2dd9c871ca543023cba"

[[constraint]]
  branch = "master"
  name = "github.com/grandcat/zeroconf"

[[constraint]]
  branch = "master"
  name = "github.com/mdlayher/ethernet"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "4.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "=1.0.1"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/pensando/grpc-gateway"

[[constraint]]
  branch = "master"
  name = "github.com/pensando/vic"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netns"

[[constraint]]
  name = "github.com/willf/bitset"
  version = "1.1.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.7.3"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v5"
  version = "5.0.58"

# Override here is needed as k8s.io/api repo is not standardized yet. ToDo
# Move to a released version when we upgrade all k8s packages
[[override]]
  name = "k8s.io/api"
  revision = "4b8fc5be9b77d91bbb6525d18591c43699a2b4e5"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[override]]
  name = "k8s.io/client-go"
  version = "v4.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "1.7"

# Needed for cni plugin types compatibility. ToDo Use a released version
[[override]]
  name = "github.com/appc/cni"
  revision = "98ff61aac32dcf2eb3044a0d5e5f1814837b3c75"

# Needed for cni plugin types compatibility. ToDo Move to a released version
[[override]]
  name = "github.com/containernetworking/cni"
  revision = "98ff61aac32dcf2eb3044a0d5e5f1814837b3c75"

# vic plugin has a hard dependency. ToDo Move this to a released version after upgrading govmomi
[[override]]
  name = "github.com/vmware/govmomi"
  revision = "35ddbd457a017bd933712fbbab56f4d6cacb32b5"

# Need override to enable raw.ListenPacket(). ToDo Move to a released version
[[override]]
  name = "github.com/mdlayher/raw"
  revision = "477f685db8a98f311907a6f91c6c7803f5213a3c"

# Overrride needed for supporting mux.RunOnAddr() call. ToDo Move to gorilla mux
[[override]]
  name = "github.com/go-martini/martini"
  revision = "fe605b5cd210047ae3bb73d2b69a5b912a9b423d"

# Override needed for supporting the correct db.Writes in TestServer. ToDo Use compatible semver
[[override]]
  name = "github.com/influxdata/influxdb"
  revision = "8b18cc445653866f71a59002f2f8524721a5d27e"

[[constraint]]
  name = "github.com/influxdata/influxql"
  branch = "master"
# Override needed for the handling unmarshal errors in Agent REST Server and NMD REST Server. ToDo Use compatible semver
[[override]]
  name = "github.com/coreos/etcd"
  version = "3.2.11"

# Override needed for compatible keymgr
[[override]]
  revision = "eda1d775a087f2a96fec7c7876ea94dea43e6027"
  name = "github.com/miekg/pkcs11"

[[override]]
  revision = "fbae0281ffd546fa6d1959fec6075ac5da7fb577"
  name = "github.com/uber-go/zap"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "github.com/gogo/protobuf"
    non-go = false
  [[prune.project]]
    name = "github.com/golang/protobuf"
    non-go = false
    unused-packages = false
  [[prune.project]]
    name = "github.com/pensando/grpc-gateway"
    unused-packages = false
    non-go = false
