# Scale config file representative of Goldman per NAPLES node scale configs
# The ordering here will be the order of objects created via Agent REST
---
objects:
- kind: Namespace
  name: scale-vrf
  count: 1
  rest-endpoint: "/api/namespaces/"
- kind: Network
  name: scale-nw
  count: 128
  rest-endpoint: "/api/networks/"
- kind: LocalEndpoint
  name: scale-ep-local
  count: 512
  rest-endpoint: "/api/endpoints/"
- kind: RemoteEndpoint
  name: scale-ep-remote
  count: 24000
  rest-endpoint: "/api/endpoints/"
- kind: App
  name: scale-app
  count: 7
  rest-endpoint: "/api/apps/"
- kind: SGPolicy
  name: scale-sg-policy
  count: 1
  rest-endpoint: "/api/security/policies/"
- kind: SGRule
  count: 58000
- kind: SecurityProfile
  name: scale-sec-profile
  count: 16
- kind: FlowExportPolicy
  name: scale-flow-mon
  count: 1
- kind: FlowMonitorRule
  count: 1000